Repository ReCoded-Org/capstone-istanbul-safe_place, pull requests merged in 2020-11, with the labels that each got.

#61 Search help page layout
  public/locales/en/translation.json
  src/components/SeekHelpSingleCard/__snapshots__/index.test.jsx.snap
  src/components/SeekHelpSingleCard/images/phone.svg
  src/components/SeekHelpSingleCard/index.jsx
  src/components/SeekHelpSingleCard/index.scss
  src/components/SliderArrow/index.jsx
  src/containers/SearchForHelpPage/index.jsx
  src/containers/SearchForHelpPage/index.scss
  src/images/chevron.svg
  src/images/chevronRight.svg
  src/images/doctorImage.svg
  src/images/icons/defaultImg.svg
  src/images/icons/doctorImage.svg
  src/images/icons/mapMarker.svg
Labels: Feat

#59 Violence test page modal
  src/components/ViolenceTestModal/__snapshots__/index.test.jsx.snap
  src/components/ViolenceTestModal/index.jsx
  src/components/ViolenceTestModal/index.scss
  src/components/ViolenceTestModal/index.test.jsx
  src/containers/ViolenceTestPage/index.jsx
Labels: Feat

#63 Search help page functionality
  public/locales/en/translation.json
  src/components/GenderViolenceMain/__snapshots__/index.test.jsx.snap
  src/components/GenderViolenceMain/index.jsx
  src/components/GenderViolenceMain/index.test.jsx
  src/components/SeekHelpMap/index.jsx
  src/components/SeekHelpSingleCard/__snapshots__/index.test.jsx.snap
  src/components/SeekHelpSingleCard/index.jsx
  src/components/SeekHelpSingleCard/index.scss
  src/containers/SearchForHelpPage/index.jsx
  src/containers/SearchForHelpPage/index.scss
  src/images/icons/locationIcon.svg
  src/images/icons/phoneIcon.svg
Labels: Feat

#58 Violence test page cards
  public/locales/en/translation.json
  src/components/ViolenceTestCards/__snapshots__/index.test.jsx.snap
  src/components/ViolenceTestCards/index.jsx
  src/components/ViolenceTestCards/index.scss
  src/components/ViolenceTestCards/index.test.jsx
  src/containers/ViolenceTestPage/index.jsx
Labels: Feat

#60 Sign in form
  package.json
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignIn/index.scss
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignInForm/index.scss
  src/components/SignInForm/index.test.js
  yarn.lock
Labels: Feat

#69 encoded google map api key
  src/components/SeekHelpMap/index.jsx
Labels: Refactor

#72 Adding link to violence test from home page
  src/components/ViolenceTest/__snapshots__/index.test.js.snap
  src/components/ViolenceTest/index.jsx
  src/components/ViolenceTest/index.test.js
Labels: Refactor

#73 Add About us page header, placeholder and translation
  public/locales/en/translation.json
  src/App.jsx
  src/containers/AboutUsPage/index.jsx
  src/containers/AboutUsPage/index.scss
Labels: Feat

#62 Feat: add sign up page
  src/App.jsx
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SignUp/index.scss
  src/components/SignUp/index.test.js
  src/components/SignUpForm/index.jsx
  src/images/womenSupportEachOther.png
Labels: Feat

#71 Creating the files and Adding header of jobs and training page.
  src/App.jsx
  src/components/JobsTrainingHeader/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHeader/index.jsx
  src/components/JobsTrainingHeader/index.scss
  src/components/JobsTrainingHeader/index.test.jsx
  src/containers/JobsTrainingPage/index.jsx
Labels: Feat

#74 Adding link to jobs and training from home page
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHome/index.jsx
  src/components/JobsTrainingHome/index.scss
  src/components/JobsTrainingHome/index.test.jsx
Labels: Refactor

#76 Our team cards component
  public/locales/en/translation.json
  src/components/OurTeamCards/__snapshots__/index.test.jsx.snap
  src/components/OurTeamCards/index.jsx
  src/components/OurTeamCards/index.scss
  src/components/OurTeamCards/index.test.jsx
  src/containers/AboutUsPage/index.jsx
  src/images/ammarSammourSmiling.jpeg
  src/images/hibaMachfejSmiling.png
  src/images/icons/githubLogo.svg
  src/images/icons/linkedInLogo.svg
  src/images/jamilBailonySmiling.png
  src/images/jennetHydyrovaSmiling.jpg
  src/images/louisLiSmiling.jpeg
  src/images/mohammadJundiSmiling.jpg
Labels: Feat

#77 adding more jobs and training opportunities to DB
  public/locales/en/translation.json
  src/components/OpportunitiesCard/index.jsx
Labels: Refactor

#81 changed link from jobs to opportunities
  src/App.jsx
Labels: Fix

#82 Chatbot feature
  package.json
  public/locales/en/translation.json
  src/App.jsx
  src/components/ChatBotMessages/images/woman.svg
  src/components/ChatBotMessages/images/womanSeeksHelp.svg
  src/components/ChatBotMessages/index.jsx
  src/components/ChatBotMessages/index.scss
  yarn.lock
Labels: Feat

#80 Added jobs training buttons component
  public/locales/en/translation.json
  src/components/JobsTrainingButtons/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingButtons/index.jsx
  src/components/JobsTrainingButtons/index.scss
  src/components/JobsTrainingButtons/index.test.jsx
Labels: Feat

#85 Firebase setup
  src/firebaseConfig.js
Labels: Feat

#79 Profile page container
  src/App.jsx
  src/components/profile/UserDetailForm/index.jsx
  src/components/profile/UserEmailForm/index.jsx
  src/components/profile/UserPasswordForm/index.jsx
  src/containers/ProfilePage/ProfileSection.jsx
  src/containers/ProfilePage/ToggleButton.jsx
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/index.jsx
  src/containers/ProfilePage/index.scss
  src/containers/ProfilePage/index.test.jsx
  src/images/defaultProfileImage.png
  src/images/icons/camera.svg
  src/style/_buttons.scss
Labels: Feat

#70 Sign up form
  src/components/Contact/__snapshots__/index.test.js.snap
  src/components/ContactForm/__snapshots__/index.test.js.snap
  src/components/ContactForm/index.jsx
  src/components/InputErrorMessage/__snapshots__/index.test.js.snap
  src/components/InputErrorMessage/index.jsx
  src/components/InputErrorMessage/index.test.js
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/SignUpForm/index.scss
  src/components/SignUpForm/index.test.jsx
  src/utils/formErrorHelpers.js
Labels: Feat

#78 Jobs and training content
  src/components/JobsTrainingButtons/index.jsx
  src/components/OpportunitiesContent/__snapshots__/index.test.jsx.snap
  src/components/OpportunitiesContent/index.jsx
  src/components/OpportunitiesContent/index.scss
  src/components/OpportunitiesContent/index.test.jsx
  src/containers/JobsTrainingPage/index.jsx
Labels: Feat

#86 Store messages from contact form
  .github/workflows/node.js.yml
  public/locales/en/translation.json
  src/components/Contact/__snapshots__/index.test.js.snap
  src/components/ContactForm/__snapshots__/index.test.js.snap
  src/components/ContactForm/index.jsx
  src/components/ContactForm/index.test.js
Labels: Feat

#90 Editing help navbar
  src/components/HelpNavbar/__snapshots__/index.test.jsx.snap
  src/components/HelpNavbar/index.jsx
  src/components/HelpNavbar/index.scss
  src/components/Navbar/index.scss
Labels: Fix

#91 Fixing the button in violence test section
  src/components/ViolenceTest/index.scss
Labels: Fix

#95 adding translation toggle
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/Navbar/__snapshots__/index.test.jsx.snap
  src/components/Navbar/index.jsx
  src/components/Navbar/index.scss
  src/i18n.config.js
  src/images/icons/language.svg
Labels: Feat

#92 Used jobsTraining button in the home page.
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHome/index.jsx
  src/components/JobsTrainingHome/index.scss
Labels: Refactor

#93 Contact form modal
  public/locales/en/translation.json
  src/components/Contact/index.jsx
  src/components/Contact/index.scss
  src/components/ContactForm/index.jsx
Labels: Feat

#94 Sign up functionality
  src/App.jsx
  src/auth/Authentication.jsx
  src/auth/PrivateRoute.jsx
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SignUpForm/index.jsx
  src/firebaseConfig.js
Labels: Feat

#96 Contact us page
  public/locales/en/translation.json
  src/App.jsx
  src/containers/ContactUsPage/__snapshots__/index.test.jsx.snap
  src/containers/ContactUsPage/index.jsx
  src/containers/ContactUsPage/index.scss
  src/containers/ContactUsPage/index.test.jsx
Labels: Feat

#101 fix header style
  src/containers/AboutUsPage/index.jsx
  src/containers/AboutUsPage/index.scss
Labels: Refactor

#104 Home headers fix
  src/components/BlogsCarouselHome/index.jsx
  src/components/BlogsCarouselHome/index.scss
  src/components/JobsTrainingHeader/index.scss
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHome/index.jsx
  src/components/JobsTrainingHome/index.scss
  src/components/SeekHelp/index.scss
Labels: Refactor

#97 Profile icon
  public/locales/en/translation.json
  src/auth/Authentication.jsx
  src/components/Navbar/SignInUpButtons/index.jsx
  src/components/Navbar/UserSetting/index.jsx
  src/components/Navbar/UserSetting/index.scss
  src/components/Navbar/__snapshots__/index.test.jsx.snap
  src/components/Navbar/index.jsx
  src/components/Navbar/index.scss
  src/style/_buttons.scss
Labels: Feat

#98 Sign in page
  public/locales/en/translation.json
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignIn/index.scss
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUp/index.jsx
  src/components/SignUpForm/index.jsx
  src/utils/authHelpers.jsx
Labels: Feat

#99 changing background color of body to $lightColor
  src/index.scss
Labels: Refactor

#103 added translation to help navbar
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/HelpNavbar/__snapshots__/index.test.jsx.snap
  src/components/HelpNavbar/index.jsx
  src/components/HelpNavbar/index.scss
Labels: Feat

#108 removing id from json
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/JobsTrainingHome/index.jsx
Labels: Fix

#107 Fix problem with clicks on sign in/up buttons
  src/auth/PrivateRoute.jsx
  src/components/Navbar/SignInUpButtons/index.jsx
  src/components/Navbar/__snapshots__/index.test.jsx.snap
Labels: Fix

#112 added translation to map header
  src/components/SeekHelp/index.jsx
Labels: Refactor

#114 Fix search help position
  src/containers/SearchForHelpPage/index.scss
Labels: Fix

#75 Blogs page
  package.json
  public/locales/en/translation.json
  src/App.jsx
  src/components/Blogs/__snapshots__/index.test.jsx.snap
  src/components/Blogs/index.jsx
  src/components/Blogs/index.scss
  src/components/Blogs/index.test.jsx
  src/containers/BlogPage/index.jsx
  src/containers/BlogPage/index.scss
  yarn.lock
Labels: Build

#110 added translation to gender violence test
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/ViolenceTest/__snapshots__/index.test.js.snap
  src/components/ViolenceTest/index.jsx
  src/components/ViolenceTest/index.scss
Labels: Fix

#115 Netlify router fix
  public/_redirects
Labels: Fix

#116 Fix _redirects file
  public/_redirects
Labels: Fix

#118 Add markers for Ankara and Izmir
  src/components/SeekHelpMap/locationData.json
Labels: Refactor

#117 Add cursor pointer to arrows
  src/components/SliderArrow/index.jsx
  src/components/SliderArrow/index.scss
Labels: Refactor

#89 Email update component and functionality
  src/components/Contact/__snapshots__/index.test.js.snap
  src/components/ContactForm/__snapshots__/index.test.js.snap
  src/components/ContactForm/index.jsx
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUpForm/index.jsx
  src/components/form/SafePlaceInput/index.jsx
  src/components/form/SafePlaceInput/index.scss
  src/components/profile/UserEmailForm/index.jsx
  src/components/profile/UserEmailForm/index.scss
  src/containers/ContactUsPage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/index.jsx
  src/containers/ProfilePage/index.scss
  src/utils/formErrorHelpers.js
  src/utils/formHelpers.js
Labels: Feat

#119 added translation to header in blog section
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/BlogsCarouselHome/index.jsx
Labels: Refactor

#120 Homepage anchor styling
  src/components/BlogsCarouselHome/index.scss
  src/components/JobsTrainingHome/index.scss
  src/style/_buttons.scss
Labels: Refactor

#145 fixed responsiveness of contact us page
  src/components/Contact/__snapshots__/index.test.js.snap
  src/components/Contact/index.jsx
  src/components/Contact/index.scss
  src/components/ContactForm/__snapshots__/index.test.js.snap
  src/components/ContactForm/index.jsx
  src/components/ContactInfo/__snapshots__/index.test.js.snap
  src/components/ContactInfo/index.jsx
  src/components/ContactInfo/index.scss
  src/containers/ContactUsPage/__snapshots__/index.test.jsx.snap
  src/containers/ContactUsPage/index.jsx
  src/containers/ContactUsPage/index.scss
Labels: Fix

#142 Add margin to opportunities header
  src/components/JobsTrainingHeader/index.scss
  src/components/OpportunitiesContent/index.scss
Labels: Fix

#127 Fix the alignment of the violence test section
  src/components/ViolenceTest/index.scss
Labels: Refactor

#141 Fixing responsiveness in about us page issues
  public/locales/ar/translation.json
  src/components/OurTeamCards/__snapshots__/index.test.jsx.snap
  src/components/OurTeamCards/index.jsx
  src/containers/AboutUsPage/index.jsx
  src/containers/AboutUsPage/index.scss
Labels: Refactor

#143 fixed opportunity buttons alignment
  src/components/JobsTrainingButtons/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingButtons/index.jsx
  src/components/JobsTrainingButtons/index.scss
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/OpportunitiesContent/__snapshots__/index.test.jsx.snap
Labels: Refactor

#111 Translating gender violence main section in home page
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/GenderViolenceMain/__snapshots__/index.test.jsx.snap
  src/components/GenderViolenceMain/index.jsx
Labels: Fix

#148 Move mock data variable
  src/components/Blogs/index.test.jsx
Labels: Refactor

#151 Profile page style fix
  src/components/profile/UserDetailForm/index.jsx
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/index.jsx
  src/containers/ProfilePage/index.scss
Labels: Fix

#150 Carousel responsiveness fix
  src/components/BlogsCarouselHome/index.jsx
  src/components/BlogsCarouselHome/index.scss
  src/components/SeekHelp/index.scss
  src/components/SeekHelpCarousel/index.scss
Labels: Fix

#149 Blog style fix
  src/components/Blogs/__snapshots__/index.test.jsx.snap
  src/components/Blogs/index.jsx
  src/components/Blogs/index.scss
  src/components/BlogsCarouselHome/index.jsx
  src/containers/BlogPage/index.jsx
Labels: Fix

#109 Single blog
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/App.jsx
  src/components/SingleBlog/__snapshots__/index.test.jsx.snap
  src/components/SingleBlog/index.jsx
  src/components/SingleBlog/index.scss
  src/components/SingleBlog/index.test.jsx
Labels: Build

#147 Contact us info translation
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/Contact/__snapshots__/index.test.js.snap
  src/components/ContactInfo/__snapshots__/index.test.js.snap
  src/components/ContactInfo/index.jsx
  src/containers/ContactUsPage/__snapshots__/index.test.jsx.snap
Labels: Fix, Refactor

#152 fixing responsiveness and margin
  src/components/OpportunitiesCard/index.scss
Labels: Refactor

#155 Fix user image
  src/containers/ProfilePage/index.jsx
Labels: Fix

#160 Fix homepage headers
  src/components/BlogsCarouselHome/index.scss
  src/components/JobsTrainingHome/index.scss
  src/components/SeekHelp/index.scss
Labels: Fix

#162 fixed small alignment issue of seek help card.
  src/components/SeekHelpSingleCard/index.scss
Labels: Refactor

#156 fix direction for Arabic language
  src/i18n.config.js
Labels: Fix

#164 Translated footer into Arabic and fixed styling related to footer.
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/Footer/__snapshots__/index.test.jsx.snap
  src/components/Footer/index.jsx
  src/components/Footer/index.scss
Labels: Refactor

#171 added translation to violence test page
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/ViolenceTestHeader/__snapshots__/index.test.jsx.snap
  src/components/ViolenceTestHeader/index.jsx
  src/components/ViolenceTestModal/__snapshots__/index.test.jsx.snap
  src/components/ViolenceTestModal/index.jsx
Labels: Refactor

#161 added blog card into single component
  src/components/BlogCard/__snapshots__/index.test.jsx.snap
  src/components/BlogCard/index.jsx
  src/components/BlogCard/index.scss
  src/components/BlogCard/index.test.jsx
  src/components/Blogs/__snapshots__/index.test.jsx.snap
  src/components/Blogs/index.jsx
  src/components/Blogs/index.scss
  src/components/BlogsCarouselHome/images/multinationalWomenImg.jpg
  src/components/BlogsCarouselHome/images/smilingWomanImg.jpg
  src/components/BlogsCarouselHome/images/womanAndManHoldingHandsImg.jpg
  src/components/BlogsCarouselHome/images/womanTalkingToTherapistImg.jpg
  src/components/BlogsCarouselHome/index.jsx
  src/components/BlogsCarouselHome/index.scss
Labels: Fix

#166 Sign in sing up margins
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignInForm/index.scss
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SignUpForm/index.jsx
  src/components/SignUpForm/index.scss
Labels: Fix

#175 Contact form bugs
  src/components/Contact/index.scss
  src/components/ContactForm/index.jsx
Labels: Fix

#170 fixing problems related Arabic language direction in home page
  public/locales/ar/translation.json
  src/components/BlogsCarouselHome/index.jsx
  src/components/BlogsCarouselHome/index.scss
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHome/index.jsx
  src/components/JobsTrainingHome/index.scss
  src/components/Navbar/index.scss
  src/components/OpportunitiesCard/index.scss
Labels: Fix

#177 Add missing translation
  public/locales/en/translation.json
Labels: Fix

#176 Add scroll up to the top of the page after render
  src/App.jsx
  src/components/ScrollToTop/index.jsx
Labels: Fix

#173 Add search help button to home page that will lead to search help page
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/BlogsCarouselHome/index.scss
  src/components/SeekHelpCarousel/index.jsx
  src/components/SeekHelpCarousel/index.scss
Labels: Fix

#181 Profile bugs
  src/components/SignIn/index.scss
  src/components/SignUp/index.scss
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/index.jsx
  src/containers/ProfilePage/index.scss
  src/style/_shapes.scss
Labels: Fix, Refactor

#185 Fix search help page responsiveness
  src/containers/SearchForHelpPage/index.jsx
Labels: Fix

#188 Job card responsiveness
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/OpportunitiesCard/__snapshots__/index.test.jsx.snap
  src/components/OpportunitiesCard/index.jsx
  src/components/OpportunitiesCard/index.scss
  src/components/OpportunitiesContent/__snapshots__/index.test.jsx.snap
Labels: Fix

#187 Fix help button responsiveness in main banner
  src/components/GenderViolenceMain/index.scss
Labels: Fix

#191 fixed position of the sign in and sign up btns in navbar
  src/components/Navbar/SignInUpButtons/index.jsx
  src/components/Navbar/__snapshots__/index.test.jsx.snap
  src/components/Navbar/index.scss
Labels: Fix

#192 Fix map responsiveness
  src/components/SeekHelp/index.scss
  src/components/SeekHelpCarousel/index.scss
Labels: Fix

#193 fixing navbar issues
  src/components/Navbar/index.scss
Labels: Fix

#196 Sign up translation
  public/locales/ar/translation.json
  public/locales/en/translation.json
  src/components/SignUp/__snapshots__/index.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SignUp/index.scss
  src/components/SignUpForm/index.jsx
  src/components/SignUpForm/index.scss
  src/components/SignUpForm/index.test.jsx
Labels: Fix

#195 Fixing responsiveness of opp cards
  src/components/JobsTrainingHome/__snapshots__/index.test.jsx.snap
  src/components/JobsTrainingHome/index.jsx
  src/components/OpportunitiesCard/__snapshots__/index.test.jsx.snap
  src/components/OpportunitiesCard/index.jsx
  src/components/OpportunitiesCard/index.scss
  src/components/OpportunitiesContent/__snapshots__/index.test.jsx.snap
Labels: Refactor

#194 Rename website in browser tab and change icon
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/safePlaceLogo.jpg
Labels: Refactor

#199 Profile and UserPasswordForm translation hooks
  public/locales/en/translation.json
  src/components/profile/UserPasswordForm/index.jsx
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
  src/containers/ProfilePage/index.jsx
Labels: Fix

#197 Sign in bugs
  public/locales/en/translation.json
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignIn/index.scss
  src/components/SignInForm/__snapshots__/index.test.js.snap
  src/components/SignInForm/index.jsx
  src/components/SignInForm/index.scss
Labels: Fix

#201 add Arabic translation for profile page
  public/locales/ar/translation.json
Labels: Fix

#200 User detail translation hooks
  public/locales/en/translation.json
  src/components/profile/UserDetailForm/countries-ar.json
  src/components/profile/UserDetailForm/countries-en.json
  src/components/profile/UserDetailForm/index.jsx
  src/containers/ProfilePage/__snapshots__/index.test.jsx.snap
Labels: Fix

#186 Translation carousel home
  src/blogApiConsts/index.js
  src/components/Blogs/index.jsx
  src/components/Blogs/index.test.jsx
  src/components/BlogsCarouselHome/index.jsx
Labels: Fix

#198 add Arabic translation
  public/locales/ar/translation.json
Labels: Fix

#204 Change nav.link to NavLink
  src/components/Navbar/SignInUpButtons/index.jsx
  src/components/Navbar/__snapshots__/index.test.jsx.snap
  src/components/Navbar/index.jsx
  src/components/Navbar/index.scss
  src/components/Navbar/index.test.jsx
  src/components/SignIn/__snapshots__/index.test.js.snap
  src/components/SignIn/index.jsx
  src/components/SignIn/index.test.js
Labels: Fix

#202 Profile arabic style bugs
  src/containers/ProfilePage/ToggleButton.jsx
  src/containers/ProfilePage/index.scss
Labels: Fix

#203 Single blog spinner
  src/components/SingleBlog/__snapshots__/index.test.jsx.snap
  src/components/SingleBlog/index.jsx
Labels: Fix

#205 add translation to email validation message
  src/containers/ProfilePage/index.jsx
  src/utils/formHelpers.js
Labels: Fix

#206 fix: braces was missed in Arabic translation file
  public/locales/ar/translation.json
Labels: Fix
